import type { ListingDetail } from '@/types/listing';

const AGENTS = {
  peter: {
    id: 'agent-peter',
    fullName: 'Peter Kamau',
    phoneNumber: '+254722111222',
    agentProfile: {
      verificationTier:  2,
      avgRating:         4.7,
      agentType:         'INDEPENDENT',
      agencyName:        'Kamau Properties',
      earbVerified:      true,
      chargesCommission: true,
      commissionMonths:  1,
      isSuspended:       false,
      totalLettings:     84,
      responseRate:      92,
      avgResponseHours:  1.5,
      createdAt:         '2022-03-10T00:00:00Z',
    },
  },
  mary: {
    id: 'agent-mary',
    fullName: 'Mary Wanjiku',
    phoneNumber: '+254733222333',
    agentProfile: {
      verificationTier:  1,
      avgRating:         4.9,
      agentType:         'LANDLORD',
      agencyName:        null,
      earbVerified:      false,
      chargesCommission: false,
      commissionMonths:  null,
      isSuspended:       false,
      totalLettings:     12,
      responseRate:      100,
      avgResponseHours:  0.5,
      createdAt:         '2023-01-15T00:00:00Z',
    },
  },
  james: {
    id: 'agent-james',
    fullName: 'James Ochieng',
    phoneNumber: '+254711333444',
    agentProfile: {
      verificationTier:  2,
      avgRating:         4.4,
      agentType:         'AGENCY',
      agencyName:        'Nairobi Realtors Ltd',
      earbVerified:      true,
      chargesCommission: true,
      commissionMonths:  1,
      isSuspended:       false,
      totalLettings:     210,
      responseRate:      78,
      avgResponseHours:  3.0,
      createdAt:         '2021-06-01T00:00:00Z',
    },
  },
  grace: {
    id: 'agent-grace',
    fullName: 'Grace Muthoni',
    phoneNumber: '+254700444555',
    agentProfile: {
      verificationTier:  0,
      avgRating:         0,
      agentType:         'INDIVIDUAL',
      agencyName:        null,
      earbVerified:      false,
      chargesCommission: false,
      commissionMonths:  null,
      isSuspended:       false,
      totalLettings:     2,
      responseRate:      null,
      avgResponseHours:  null,
      createdAt:         '2024-11-01T00:00:00Z',
    },
  },
};

const AREAS = {
  ruaka:       { id: 'area-ruaka',       name: 'Ruaka',       slug: 'ruaka',       waterSituation: 'TANK',     powerReliability: 'OCCASIONAL', noiseLevel: 'MODERATE', securityLevel: 'GOOD',     areaNotes: 'Fast-growing suburb popular with young professionals. 20 min to Westlands.' },
  kilimani:    { id: 'area-kilimani',    name: 'Kilimani',    slug: 'kilimani',    waterSituation: 'HOURS_24', powerReliability: 'RELIABLE',   noiseLevel: 'MODERATE', securityLevel: 'EXCELLENT',areaNotes: 'Upmarket area close to Yaya Centre and Valley Arcade. Quiet residential streets.' },
  southb:      { id: 'area-southb',      name: 'South B',     slug: 'south-b',     waterSituation: 'RATIONED', powerReliability: 'OCCASIONAL', noiseLevel: 'MODERATE', securityLevel: 'GOOD',     areaNotes: 'Established estate near SGR Syokimau terminus. Water rationed Mon, Wed, Fri.' },
  westlands:   { id: 'area-westlands',   name: 'Westlands',   slug: 'westlands',   waterSituation: 'HOURS_24', powerReliability: 'RELIABLE',   noiseLevel: 'NOISY',    securityLevel: 'EXCELLENT',areaNotes: 'Prime commercial/residential hub. Noisy near Westlands roundabout; quieter side streets.' },
  kasarani:    { id: 'area-kasarani',    name: 'Kasarani',    slug: 'kasarani',    waterSituation: 'TANK',     powerReliability: 'OCCASIONAL', noiseLevel: 'MODERATE', securityLevel: 'GOOD',     areaNotes: 'Near Moi International Sports Centre. Good value for money; busy during events.' },
  embakasi:    { id: 'area-embakasi',    name: 'Embakasi',    slug: 'embakasi',    waterSituation: 'TANK',     powerReliability: 'FREQUENT',   noiseLevel: 'MODERATE', securityLevel: 'MODERATE', areaNotes: 'Near JKIA. Affordable; power outages can be frequent in some zones.' },
  rongai:      { id: 'area-rongai',      name: 'Rongai',      slug: 'rongai',      waterSituation: 'BOREHOLE', powerReliability: 'RELIABLE',   noiseLevel: 'QUIET',    securityLevel: 'GOOD',     areaNotes: 'Peaceful satellite town south of Nairobi. Long commute ~1hr to CBD in traffic.' },
  kileleshwa:  { id: 'area-kileleshwa',  name: 'Kileleshwa',  slug: 'kileleshwa',  waterSituation: 'HOURS_24', powerReliability: 'RELIABLE',   noiseLevel: 'QUIET',    securityLevel: 'EXCELLENT',areaNotes: 'Leafy, quiet suburb. Very low crime. Sought-after for families.' },
  buruburu:    { id: 'area-buruburu',    name: 'Buruburu',    slug: 'buruburu',    waterSituation: 'RATIONED', powerReliability: 'OCCASIONAL', noiseLevel: 'MODERATE', securityLevel: 'GOOD',     areaNotes: 'Large estate east of CBD. Water scheduled. Good road network.' },
  ngong:       { id: 'area-ngong',       name: 'Ngong',       slug: 'ngong',       waterSituation: 'TANK',     powerReliability: 'OCCASIONAL', noiseLevel: 'QUIET',    securityLevel: 'GOOD',     areaNotes: 'Cool climate at altitude. Scenic views. About 30km from CBD.' },
  athiriver:   { id: 'area-athiriver',   name: 'Athi River',  slug: 'athi-river',  waterSituation: 'TANK',     powerReliability: 'RELIABLE',   noiseLevel: 'QUIET',    securityLevel: 'MODERATE', areaNotes: 'Industrial town near EPZ. Very affordable. Growing fast with SGR station.' },
  kitengela:   { id: 'area-kitengela',   name: 'Kitengela',   slug: 'kitengela',   waterSituation: 'TANK',     powerReliability: 'RELIABLE',   noiseLevel: 'MODERATE', securityLevel: 'GOOD',     areaNotes: 'Fast-growing dormitory town. 30–45 min to CBD. Good amenities.' },
};

function daysBack(n: number): string {
  return new Date(Date.now() - n * 86400000).toISOString();
}

export const MOCK_LISTINGS: ListingDetail[] = [
  {
    id: 'lst-001',
    title: 'Modern Bedsitter — 5 min walk to Ruaka Stage',
    unitType: 'BEDSITTER',
    addressText: 'Jumuia Place, Ruaka',
    monthlyRent: 9500,
    depositMonths: 1,
    advanceMonths: 1,
    commissionAmount: null,
    commissionPayer: 'NONE',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'TANK', power_backup: 'NONE', security: ['Watchman'], parking: false, internet: false, lift: false, balcony: false, pets_allowed: false, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(1),
    viewCount: 214,
    whatsappTapCount: 31,
    saveCount: 18,
    createdAt: daysBack(12),
    updatedAt: daysBack(1),
    expiresAt: daysBack(-18),
    description: 'Cosy self-contained bedsitter on ground floor of a 4-storey building. Hot shower, fitted kitchen, lockable gate. 5-minute walk to Ruaka matatu stage — Route 111 to Westlands and CBD.',
    lat: -1.2112, lng: 36.7977,
    floorNumber: 0, totalFloors: 4,
    availableFrom: null,
    estWaterBill: 500, estElectricityBill: 800, serviceCharge: 500, garbageFee: 200,
    reportCount: 0,
    area: AREAS.ruaka,
    photos: [],
    agent: AGENTS.grace,
    matautuRoutes: [
      { walkMinutes: 5, distanceMeters: 350, nearestStopName: 'Ruaka Stage',
        route: { routeNumber: '111', name: 'Ruaka – Westlands – CBD', origin: 'Ruaka', destination: 'CBD', frequencyMinutes: 15, operatingHours: '5:30am – 10pm' } },
    ],
  },

  {
    id: 'lst-002',
    title: 'Spacious 2-Bedroom Apartment — Furnished, Kilimani',
    unitType: 'TWO_BED',
    addressText: 'Rose Avenue, off Ngong Road',
    monthlyRent: 45000,
    depositMonths: 2,
    advanceMonths: 1,
    commissionAmount: 45000,
    commissionPayer: 'TENANT',
    furnishing: 'FURNISHED',
    selfContained: true,
    amenities: { water: 'HOURS_24', power_backup: 'GENERATOR', security: ['Electric fence', 'Watchman', 'CCTV'], parking: true, internet: true, lift: false, balcony: true, pets_allowed: false, gym: false, swimming_pool: true },
    isFeatured: true,
    freshnessConfirmedAt: daysBack(0),
    viewCount: 892,
    whatsappTapCount: 74,
    saveCount: 61,
    createdAt: daysBack(5),
    updatedAt: daysBack(0),
    expiresAt: daysBack(-25),
    description: 'Beautifully furnished 2-bed apartment in Kilimani\'s most sought-after block. Master en-suite, modern kitchen with oven, high-speed fibre internet included. Pool and gym on-site. 24hr water and backup generator.',
    lat: -1.2917, lng: 36.7869,
    floorNumber: 4, totalFloors: 8,
    availableFrom: new Date(Date.now() + 7 * 86400000).toISOString().split('T')[0],
    estWaterBill: 0, estElectricityBill: 3500, serviceCharge: 3000, garbageFee: 300,
    reportCount: 0,
    area: AREAS.kilimani,
    photos: [],
    agent: AGENTS.james,
    matautuRoutes: [
      { walkMinutes: 8, distanceMeters: 600, nearestStopName: 'Valley Arcade',
        route: { routeNumber: '23', name: 'Westlands – CBD – South B', origin: 'Westlands', destination: 'South B', frequencyMinutes: 10, operatingHours: '5am – 11pm' } },
    ],
  },

  {
    id: 'lst-003',
    title: '1-Bedroom Flat — South B, Near SGR Terminus',
    unitType: 'ONE_BED',
    addressText: 'South B Estate, Phase 3',
    monthlyRent: 18000,
    depositMonths: 1,
    advanceMonths: 0,
    commissionAmount: null,
    commissionPayer: 'LANDLORD',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'RATIONED', power_backup: 'NONE', security: ['Watchman', 'Electric fence'], parking: true, internet: false, lift: false, balcony: false, pets_allowed: false, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(3),
    viewCount: 355,
    whatsappTapCount: 42,
    saveCount: 27,
    createdAt: daysBack(20),
    updatedAt: daysBack(3),
    expiresAt: daysBack(-10),
    description: '1-bed on 2nd floor of a quiet block. Parking space included. Walking distance to Syokimau SGR station and major supermarkets. Water scheduled Mon/Wed/Fri — tank available. No agency fee.',
    lat: -1.3147, lng: 36.8481,
    floorNumber: 2, totalFloors: 5,
    availableFrom: null,
    estWaterBill: 600, estElectricityBill: 1200, serviceCharge: 800, garbageFee: 200,
    reportCount: 0,
    area: AREAS.southb,
    photos: [],
    agent: AGENTS.mary,
    matautuRoutes: [
      { walkMinutes: 10, distanceMeters: 800, nearestStopName: 'South B Stage',
        route: { routeNumber: '34', name: 'South B – CBD', origin: 'South B', destination: 'CBD', frequencyMinutes: 12, operatingHours: '5:30am – 10:30pm' } },
    ],
  },

  {
    id: 'lst-004',
    title: 'Studio Apartment — Westlands, All Bills Inclusive',
    unitType: 'STUDIO',
    addressText: 'Westlands Road, Near Sarit Centre',
    monthlyRent: 28000,
    depositMonths: 1,
    advanceMonths: 1,
    commissionAmount: null,
    commissionPayer: 'NONE',
    furnishing: 'SEMI',
    selfContained: true,
    amenities: { water: 'HOURS_24', power_backup: 'GENERATOR', security: ['CCTV', 'Concierge', 'Electric fence'], parking: false, internet: true, lift: true, balcony: false, pets_allowed: false, gym: true, swimming_pool: false },
    isFeatured: true,
    freshnessConfirmedAt: daysBack(2),
    viewCount: 641,
    whatsappTapCount: 55,
    saveCount: 44,
    createdAt: daysBack(8),
    updatedAt: daysBack(2),
    expiresAt: daysBack(-22),
    description: 'Compact studio on 6th floor with great views. Comes with bed, wardrobe and breakfast bar. Water, internet and service charge included in rent. Gym on-site. Steps from Sarit Centre and Westgate Mall.',
    lat: -1.2660, lng: 36.8031,
    floorNumber: 6, totalFloors: 12,
    availableFrom: null,
    estWaterBill: 0, estElectricityBill: 0, serviceCharge: 0, garbageFee: 0,
    reportCount: 0,
    area: AREAS.westlands,
    photos: [],
    agent: AGENTS.peter,
    matautuRoutes: [
      { walkMinutes: 3, distanceMeters: 200, nearestStopName: 'Westlands Roundabout',
        route: { routeNumber: '46', name: 'Westlands – CBD', origin: 'Westlands', destination: 'CBD', frequencyMinutes: 8, operatingHours: '5am – midnight' } },
    ],
  },

  {
    id: 'lst-005',
    title: '2-Bedroom Apartment — Kasarani, Near Moi Sports Centre',
    unitType: 'TWO_BED',
    addressText: 'Marurui Estate, Kasarani',
    monthlyRent: 20000,
    depositMonths: 1,
    advanceMonths: 1,
    commissionAmount: 20000,
    commissionPayer: 'TENANT',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'TANK', power_backup: 'NONE', security: ['Watchman'], parking: true, internet: false, lift: false, balcony: true, pets_allowed: true, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(5),
    viewCount: 178,
    whatsappTapCount: 19,
    saveCount: 11,
    createdAt: daysBack(18),
    updatedAt: daysBack(5),
    expiresAt: daysBack(-12),
    description: 'Spacious 2-bed on 1st floor with balcony. Pets allowed. Parking for one car. Close to Kasarani Stadium, TRM Mall and Nairobi Safari Park. Good public transport links.',
    lat: -1.2220, lng: 36.8953,
    floorNumber: 1, totalFloors: 4,
    availableFrom: null,
    estWaterBill: 700, estElectricityBill: 1800, serviceCharge: 500, garbageFee: 200,
    reportCount: 0,
    area: AREAS.kasarani,
    photos: [],
    agent: AGENTS.james,
    matautuRoutes: [
      { walkMinutes: 12, distanceMeters: 900, nearestStopName: 'Moi Sports Centre',
        route: { routeNumber: '58', name: 'Kasarani – CBD', origin: 'Kasarani', destination: 'CBD', frequencyMinutes: 15, operatingHours: '5:30am – 10pm' } },
    ],
  },

  {
    id: 'lst-006',
    title: '1-Bedroom Flat — Embakasi, 10 min to JKIA',
    unitType: 'ONE_BED',
    addressText: 'Eastern Bypass Road, Embakasi',
    monthlyRent: 13500,
    depositMonths: 1,
    advanceMonths: 0,
    commissionAmount: null,
    commissionPayer: 'NONE',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'TANK', power_backup: 'NONE', security: ['Watchman', 'Gate'], parking: false, internet: false, lift: false, balcony: false, pets_allowed: false, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(7),
    viewCount: 119,
    whatsappTapCount: 14,
    saveCount: 7,
    createdAt: daysBack(25),
    updatedAt: daysBack(7),
    expiresAt: daysBack(-5),
    description: 'Clean 1-bed near Eastern Bypass. Ideal for airport workers and logistics staff. Quiet block, hot shower, large windows. No agency fee.',
    lat: -1.3190, lng: 36.9257,
    floorNumber: 2, totalFloors: 3,
    availableFrom: null,
    estWaterBill: 500, estElectricityBill: 900, serviceCharge: 400, garbageFee: 200,
    reportCount: 0,
    area: AREAS.embakasi,
    photos: [],
    agent: AGENTS.grace,
    matautuRoutes: [
      { walkMinutes: 15, distanceMeters: 1100, nearestStopName: 'Embakasi Stage',
        route: { routeNumber: '48', name: 'Embakasi – CBD', origin: 'Embakasi', destination: 'CBD', frequencyMinutes: 20, operatingHours: '5am – 9:30pm' } },
    ],
  },

  {
    id: 'lst-007',
    title: 'Bedsitter — Rongai, Peaceful & Secure',
    unitType: 'BEDSITTER',
    addressText: 'Tumaini Estate, Rongai',
    monthlyRent: 8000,
    depositMonths: 1,
    advanceMonths: 0,
    commissionAmount: null,
    commissionPayer: 'NONE',
    furnishing: 'UNFURNISHED',
    selfContained: false,
    amenities: { water: 'BOREHOLE', power_backup: 'NONE', security: ['Watchman'], parking: false, internet: false, lift: false, balcony: false, pets_allowed: false, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(2),
    viewCount: 88,
    whatsappTapCount: 12,
    saveCount: 5,
    createdAt: daysBack(15),
    updatedAt: daysBack(2),
    expiresAt: daysBack(-15),
    description: 'Budget bedsitter in quiet Rongai estate. Shared bathroom with only one neighbour. Reliable borehole water. Great for someone working from home or studying. Very safe neighbourhood.',
    lat: -1.3989, lng: 36.7451,
    floorNumber: 0, totalFloors: 2,
    availableFrom: null,
    estWaterBill: 300, estElectricityBill: 500, serviceCharge: 300, garbageFee: 100,
    reportCount: 0,
    area: AREAS.rongai,
    photos: [],
    agent: AGENTS.mary,
    matautuRoutes: [
      { walkMinutes: 10, distanceMeters: 750, nearestStopName: 'Rongai Town Stage',
        route: { routeNumber: '125', name: 'Rongai – CBD', origin: 'Rongai', destination: 'CBD', frequencyMinutes: 20, operatingHours: '5am – 9pm' } },
    ],
  },

  {
    id: 'lst-008',
    title: 'Luxury 3-Bedroom Apartment — Kileleshwa, All Ensuite',
    unitType: 'THREE_BED',
    addressText: 'Kileleshwa Close, off Gitanga Road',
    monthlyRent: 85000,
    depositMonths: 2,
    advanceMonths: 1,
    commissionAmount: 85000,
    commissionPayer: 'TENANT',
    furnishing: 'FURNISHED',
    selfContained: true,
    amenities: { water: 'HOURS_24', power_backup: 'GENERATOR', security: ['Electric fence', 'CCTV', 'Concierge', 'Watchman'], parking: true, internet: true, lift: true, balcony: true, pets_allowed: false, gym: true, swimming_pool: true },
    isFeatured: true,
    freshnessConfirmedAt: daysBack(0),
    viewCount: 1240,
    whatsappTapCount: 98,
    saveCount: 87,
    createdAt: daysBack(3),
    updatedAt: daysBack(0),
    expiresAt: daysBack(-27),
    description: 'Premium 3-bed apartment in Nairobi\'s most sought-after leafy suburb. All three bedrooms ensuite, master with walk-in wardrobe. Chef\'s kitchen, open-plan living, large balcony. High-speed fibre internet, backup generator, 24hr concierge.',
    lat: -1.2852, lng: 36.7756,
    floorNumber: 5, totalFloors: 10,
    availableFrom: null,
    estWaterBill: 0, estElectricityBill: 5000, serviceCharge: 5000, garbageFee: 500,
    reportCount: 0,
    area: AREAS.kileleshwa,
    photos: [],
    agent: AGENTS.peter,
    matautuRoutes: [
      { walkMinutes: 7, distanceMeters: 500, nearestStopName: 'Kileleshwa Stage',
        route: { routeNumber: '23', name: 'Westlands – CBD – South B', origin: 'Westlands', destination: 'South B', frequencyMinutes: 10, operatingHours: '5am – 11pm' } },
    ],
  },

  {
    id: 'lst-009',
    title: '1-Bedroom — Buruburu Phase 2, Near Shopping Centre',
    unitType: 'ONE_BED',
    addressText: 'Buruburu Phase 2, Jogoo Road',
    monthlyRent: 15000,
    depositMonths: 1,
    advanceMonths: 1,
    commissionAmount: null,
    commissionPayer: 'LANDLORD',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'RATIONED', power_backup: 'NONE', security: ['Watchman', 'Gate'], parking: false, internet: false, lift: false, balcony: false, pets_allowed: false, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(4),
    viewCount: 203,
    whatsappTapCount: 28,
    saveCount: 16,
    createdAt: daysBack(22),
    updatedAt: daysBack(4),
    expiresAt: daysBack(-8),
    description: 'Clean and bright 1-bed in the heart of Buruburu estate. Steps from Buruburu Shopping Centre, schools and clinics. Good transport to CBD via Jogoo Road. Landlord pays agency fee.',
    lat: -1.2882, lng: 36.8729,
    floorNumber: 1, totalFloors: 3,
    availableFrom: null,
    estWaterBill: 600, estElectricityBill: 1000, serviceCharge: 500, garbageFee: 200,
    reportCount: 0,
    area: AREAS.buruburu,
    photos: [],
    agent: AGENTS.james,
    matautuRoutes: [
      { walkMinutes: 8, distanceMeters: 600, nearestStopName: 'Buruburu Stage',
        route: { routeNumber: '46', name: 'Buruburu – CBD', origin: 'Buruburu', destination: 'CBD', frequencyMinutes: 12, operatingHours: '5:30am – 10pm' } },
    ],
  },

  {
    id: 'lst-010',
    title: '2-Bedroom — Ngong Town, Cool Climate & Great Views',
    unitType: 'TWO_BED',
    addressText: 'Ngong Town, Near County Hospital',
    monthlyRent: 16000,
    depositMonths: 1,
    advanceMonths: 1,
    commissionAmount: null,
    commissionPayer: 'NONE',
    furnishing: 'SEMI',
    selfContained: true,
    amenities: { water: 'TANK', power_backup: 'NONE', security: ['Watchman', 'Gate'], parking: true, internet: false, lift: false, balcony: true, pets_allowed: true, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(6),
    viewCount: 134,
    whatsappTapCount: 16,
    saveCount: 9,
    createdAt: daysBack(28),
    updatedAt: daysBack(6),
    expiresAt: daysBack(-2),
    description: 'Semi-furnished 2-bed with spectacular Ngong Hills views from the balcony. Cool climate year-round. Secure compound with parking. Great for families. 30 min drive to CBD, 20 min to Karen.',
    lat: -1.3657, lng: 36.6570,
    floorNumber: 2, totalFloors: 4,
    availableFrom: null,
    estWaterBill: 600, estElectricityBill: 1200, serviceCharge: 400, garbageFee: 200,
    reportCount: 0,
    area: AREAS.ngong,
    photos: [],
    agent: AGENTS.mary,
    matautuRoutes: [
      { walkMinutes: 12, distanceMeters: 900, nearestStopName: 'Ngong Town Stage',
        route: { routeNumber: '126', name: 'Ngong – CBD', origin: 'Ngong', destination: 'CBD', frequencyMinutes: 25, operatingHours: '5am – 9pm' } },
    ],
  },

  {
    id: 'lst-011',
    title: 'Budget Bedsitter — Athi River, Near SGR Station',
    unitType: 'BEDSITTER',
    addressText: 'Athi River Town, EPZ Road',
    monthlyRent: 7500,
    depositMonths: 1,
    advanceMonths: 0,
    commissionAmount: null,
    commissionPayer: 'NONE',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'TANK', power_backup: 'NONE', security: ['Watchman'], parking: false, internet: false, lift: false, balcony: false, pets_allowed: false, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: null,
    viewCount: 76,
    whatsappTapCount: 9,
    saveCount: 3,
    createdAt: daysBack(30),
    updatedAt: daysBack(30),
    expiresAt: daysBack(0),
    description: 'Affordable self-contained bedsitter. Ideal for EPZ workers or SGR commuters. Hot shower, fitted kitchenette. 5 min boda-boda to Athi River SGR station.',
    lat: -1.4571, lng: 36.9800,
    floorNumber: 0, totalFloors: 2,
    availableFrom: null,
    estWaterBill: 300, estElectricityBill: 500, serviceCharge: 200, garbageFee: 100,
    reportCount: 0,
    area: AREAS.athiriver,
    photos: [],
    agent: AGENTS.grace,
    matautuRoutes: [
      { walkMinutes: 20, distanceMeters: 1500, nearestStopName: 'Athi River Stage',
        route: { routeNumber: '34', name: 'Athi River – CBD', origin: 'Athi River', destination: 'CBD', frequencyMinutes: 30, operatingHours: '5am – 8pm' } },
    ],
  },

  {
    id: 'lst-012',
    title: '2-Bedroom Apartment — Kitengela, Gated Community',
    unitType: 'TWO_BED',
    addressText: 'Milimani Estate, Kitengela',
    monthlyRent: 14000,
    depositMonths: 2,
    advanceMonths: 0,
    commissionAmount: null,
    commissionPayer: 'LANDLORD',
    furnishing: 'UNFURNISHED',
    selfContained: true,
    amenities: { water: 'TANK', power_backup: 'SOLAR', security: ['Electric fence', 'CCTV', 'Watchman'], parking: true, internet: false, lift: false, balcony: true, pets_allowed: true, gym: false, swimming_pool: false },
    isFeatured: false,
    freshnessConfirmedAt: daysBack(1),
    viewCount: 267,
    whatsappTapCount: 33,
    saveCount: 21,
    createdAt: daysBack(10),
    updatedAt: daysBack(1),
    expiresAt: daysBack(-20),
    description: 'New 2-bed in a gated estate. Solar backup for common areas. Spacious rooms, balcony with garden views. Pets welcome. Landlord pays agency fee. 35 min to CBD via Mombasa Road.',
    lat: -1.4752, lng: 36.9726,
    floorNumber: 1, totalFloors: 3,
    availableFrom: null,
    estWaterBill: 600, estElectricityBill: 1000, serviceCharge: 500, garbageFee: 200,
    reportCount: 0,
    area: AREAS.kitengela,
    photos: [],
    agent: AGENTS.peter,
    matautuRoutes: [
      { walkMinutes: 15, distanceMeters: 1100, nearestStopName: 'Kitengela Stage',
        route: { routeNumber: '126', name: 'Kitengela – CBD', origin: 'Kitengela', destination: 'CBD', frequencyMinutes: 30, operatingHours: '5am – 9pm' } },
    ],
  },
];
